blank_issues_enabled: false
contact_links:
  - name: Contribute lexical data via email
    url: mailto:terrill.schrock@gmail.com
    about: Currently, lexical data contributions are accepted by email rather than through GitHub. Please email completed contribution spreadsheets directly.
